//sample api response from github api user repos detail request
export const GitHubData = [
    {
        "id": 573914443,
        "node_id": "R_kgDOIjU9Sw",
        "name": "mahashipping-web-app",
        "full_name": "SaiBarathR/mahashipping-web-app",
        "private": false,
        "owner": {
            "login": "SaiBarathR",
            "id": 58382813,
            "node_id": "MDQ6VXNlcjU4MzgyODEz",
            "avatar_url": "https://avatars.githubusercontent.com/u/58382813?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/SaiBarathR",
            "html_url": "https://github.com/SaiBarathR",
            "followers_url": "https://api.github.com/users/SaiBarathR/followers",
            "following_url": "https://api.github.com/users/SaiBarathR/following{/other_user}",
            "gists_url": "https://api.github.com/users/SaiBarathR/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/SaiBarathR/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/SaiBarathR/subscriptions",
            "organizations_url": "https://api.github.com/users/SaiBarathR/orgs",
            "repos_url": "https://api.github.com/users/SaiBarathR/repos",
            "events_url": "https://api.github.com/users/SaiBarathR/events{/privacy}",
            "received_events_url": "https://api.github.com/users/SaiBarathR/received_events",
            "type": "User",
            "site_admin": false
        },
        "html_url": "https://github.com/SaiBarathR/mahashipping-web-app",
        "description": "Currently Creating this Logistics Site for MahaShipping Services, first-phase design is done. Working on to integrate Icegate's API for tracking and shipping calculations. ",
        "fork": false,
        "url": "https://api.github.com/repos/SaiBarathR/mahashipping-web-app",
        "forks_url": "https://api.github.com/repos/SaiBarathR/mahashipping-web-app/forks",
        "keys_url": "https://api.github.com/repos/SaiBarathR/mahashipping-web-app/keys{/key_id}",
        "collaborators_url": "https://api.github.com/repos/SaiBarathR/mahashipping-web-app/collaborators{/collaborator}",
        "teams_url": "https://api.github.com/repos/SaiBarathR/mahashipping-web-app/teams",
        "hooks_url": "https://api.github.com/repos/SaiBarathR/mahashipping-web-app/hooks",
        "issue_events_url": "https://api.github.com/repos/SaiBarathR/mahashipping-web-app/issues/events{/number}",
        "events_url": "https://api.github.com/repos/SaiBarathR/mahashipping-web-app/events",
        "assignees_url": "https://api.github.com/repos/SaiBarathR/mahashipping-web-app/assignees{/user}",
        "branches_url": "https://api.github.com/repos/SaiBarathR/mahashipping-web-app/branches{/branch}",
        "tags_url": "https://api.github.com/repos/SaiBarathR/mahashipping-web-app/tags",
        "blobs_url": "https://api.github.com/repos/SaiBarathR/mahashipping-web-app/git/blobs{/sha}",
        "git_tags_url": "https://api.github.com/repos/SaiBarathR/mahashipping-web-app/git/tags{/sha}",
        "git_refs_url": "https://api.github.com/repos/SaiBarathR/mahashipping-web-app/git/refs{/sha}",
        "trees_url": "https://api.github.com/repos/SaiBarathR/mahashipping-web-app/git/trees{/sha}",
        "statuses_url": "https://api.github.com/repos/SaiBarathR/mahashipping-web-app/statuses/{sha}",
        "languages_url": "https://api.github.com/repos/SaiBarathR/mahashipping-web-app/languages",
        "stargazers_url": "https://api.github.com/repos/SaiBarathR/mahashipping-web-app/stargazers",
        "contributors_url": "https://api.github.com/repos/SaiBarathR/mahashipping-web-app/contributors",
        "subscribers_url": "https://api.github.com/repos/SaiBarathR/mahashipping-web-app/subscribers",
        "subscription_url": "https://api.github.com/repos/SaiBarathR/mahashipping-web-app/subscription",
        "commits_url": "https://api.github.com/repos/SaiBarathR/mahashipping-web-app/commits{/sha}",
        "git_commits_url": "https://api.github.com/repos/SaiBarathR/mahashipping-web-app/git/commits{/sha}",
        "comments_url": "https://api.github.com/repos/SaiBarathR/mahashipping-web-app/comments{/number}",
        "issue_comment_url": "https://api.github.com/repos/SaiBarathR/mahashipping-web-app/issues/comments{/number}",
        "contents_url": "https://api.github.com/repos/SaiBarathR/mahashipping-web-app/contents/{+path}",
        "compare_url": "https://api.github.com/repos/SaiBarathR/mahashipping-web-app/compare/{base}...{head}",
        "merges_url": "https://api.github.com/repos/SaiBarathR/mahashipping-web-app/merges",
        "archive_url": "https://api.github.com/repos/SaiBarathR/mahashipping-web-app/{archive_format}{/ref}",
        "downloads_url": "https://api.github.com/repos/SaiBarathR/mahashipping-web-app/downloads",
        "issues_url": "https://api.github.com/repos/SaiBarathR/mahashipping-web-app/issues{/number}",
        "pulls_url": "https://api.github.com/repos/SaiBarathR/mahashipping-web-app/pulls{/number}",
        "milestones_url": "https://api.github.com/repos/SaiBarathR/mahashipping-web-app/milestones{/number}",
        "notifications_url": "https://api.github.com/repos/SaiBarathR/mahashipping-web-app/notifications{?since,all,participating}",
        "labels_url": "https://api.github.com/repos/SaiBarathR/mahashipping-web-app/labels{/name}",
        "releases_url": "https://api.github.com/repos/SaiBarathR/mahashipping-web-app/releases{/id}",
        "deployments_url": "https://api.github.com/repos/SaiBarathR/mahashipping-web-app/deployments",
        "created_at": "2022-12-03T20:42:26Z",
        "updated_at": "2023-07-09T17:45:44Z",
        "pushed_at": "2023-06-28T13:03:45Z",
        "git_url": "git://github.com/SaiBarathR/mahashipping-web-app.git",
        "ssh_url": "git@github.com:SaiBarathR/mahashipping-web-app.git",
        "clone_url": "https://github.com/SaiBarathR/mahashipping-web-app.git",
        "svn_url": "https://github.com/SaiBarathR/mahashipping-web-app",
        "homepage": "https://mahashipping.netlify.app/",
        "size": 1257,
        "stargazers_count": 1,
        "watchers_count": 1,
        "language": "JavaScript",
        "has_issues": true,
        "has_projects": true,
        "has_downloads": true,
        "has_wiki": true,
        "has_pages": false,
        "has_discussions": false,
        "forks_count": 0,
        "mirror_url": null,
        "archived": false,
        "disabled": false,
        "open_issues_count": 0,
        "license": {
            "key": "mit",
            "name": "MIT License",
            "spdx_id": "MIT",
            "url": "https://api.github.com/licenses/mit",
            "node_id": "MDc6TGljZW5zZTEz"
        },
        "allow_forking": true,
        "is_template": false,
        "web_commit_signoff_required": false,
        "topics": [
            "framer-motion",
            "mysql",
            "reactjs",
            "responsive-web-design",
            "rest-api",
            "spring-boot"
        ],
        "visibility": "public",
        "forks": 0,
        "open_issues": 0,
        "watchers": 1,
        "default_branch": "main"
    },
    {
        "id": 662985475,
        "node_id": "R_kgDOJ4RbAw",
        "name": "personal-portfolio",
        "full_name": "SaiBarathR/personal-portfolio",
        "private": false,
        "owner": {
            "login": "SaiBarathR",
            "id": 58382813,
            "node_id": "MDQ6VXNlcjU4MzgyODEz",
            "avatar_url": "https://avatars.githubusercontent.com/u/58382813?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/SaiBarathR",
            "html_url": "https://github.com/SaiBarathR",
            "followers_url": "https://api.github.com/users/SaiBarathR/followers",
            "following_url": "https://api.github.com/users/SaiBarathR/following{/other_user}",
            "gists_url": "https://api.github.com/users/SaiBarathR/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/SaiBarathR/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/SaiBarathR/subscriptions",
            "organizations_url": "https://api.github.com/users/SaiBarathR/orgs",
            "repos_url": "https://api.github.com/users/SaiBarathR/repos",
            "events_url": "https://api.github.com/users/SaiBarathR/events{/privacy}",
            "received_events_url": "https://api.github.com/users/SaiBarathR/received_events",
            "type": "User",
            "site_admin": false
        },
        "html_url": "https://github.com/SaiBarathR/personal-portfolio",
        "description": "Personal portfolio site, using realtime project details from git hub api's, and silky smooth css animations with perfect responsiveness in all type of devices and browsers. Anyone can clone it and rearrange the components according to your needs.",
        "fork": false,
        "url": "https://api.github.com/repos/SaiBarathR/personal-portfolio",
        "forks_url": "https://api.github.com/repos/SaiBarathR/personal-portfolio/forks",
        "keys_url": "https://api.github.com/repos/SaiBarathR/personal-portfolio/keys{/key_id}",
        "collaborators_url": "https://api.github.com/repos/SaiBarathR/personal-portfolio/collaborators{/collaborator}",
        "teams_url": "https://api.github.com/repos/SaiBarathR/personal-portfolio/teams",
        "hooks_url": "https://api.github.com/repos/SaiBarathR/personal-portfolio/hooks",
        "issue_events_url": "https://api.github.com/repos/SaiBarathR/personal-portfolio/issues/events{/number}",
        "events_url": "https://api.github.com/repos/SaiBarathR/personal-portfolio/events",
        "assignees_url": "https://api.github.com/repos/SaiBarathR/personal-portfolio/assignees{/user}",
        "branches_url": "https://api.github.com/repos/SaiBarathR/personal-portfolio/branches{/branch}",
        "tags_url": "https://api.github.com/repos/SaiBarathR/personal-portfolio/tags",
        "blobs_url": "https://api.github.com/repos/SaiBarathR/personal-portfolio/git/blobs{/sha}",
        "git_tags_url": "https://api.github.com/repos/SaiBarathR/personal-portfolio/git/tags{/sha}",
        "git_refs_url": "https://api.github.com/repos/SaiBarathR/personal-portfolio/git/refs{/sha}",
        "trees_url": "https://api.github.com/repos/SaiBarathR/personal-portfolio/git/trees{/sha}",
        "statuses_url": "https://api.github.com/repos/SaiBarathR/personal-portfolio/statuses/{sha}",
        "languages_url": "https://api.github.com/repos/SaiBarathR/personal-portfolio/languages",
        "stargazers_url": "https://api.github.com/repos/SaiBarathR/personal-portfolio/stargazers",
        "contributors_url": "https://api.github.com/repos/SaiBarathR/personal-portfolio/contributors",
        "subscribers_url": "https://api.github.com/repos/SaiBarathR/personal-portfolio/subscribers",
        "subscription_url": "https://api.github.com/repos/SaiBarathR/personal-portfolio/subscription",
        "commits_url": "https://api.github.com/repos/SaiBarathR/personal-portfolio/commits{/sha}",
        "git_commits_url": "https://api.github.com/repos/SaiBarathR/personal-portfolio/git/commits{/sha}",
        "comments_url": "https://api.github.com/repos/SaiBarathR/personal-portfolio/comments{/number}",
        "issue_comment_url": "https://api.github.com/repos/SaiBarathR/personal-portfolio/issues/comments{/number}",
        "contents_url": "https://api.github.com/repos/SaiBarathR/personal-portfolio/contents/{+path}",
        "compare_url": "https://api.github.com/repos/SaiBarathR/personal-portfolio/compare/{base}...{head}",
        "merges_url": "https://api.github.com/repos/SaiBarathR/personal-portfolio/merges",
        "archive_url": "https://api.github.com/repos/SaiBarathR/personal-portfolio/{archive_format}{/ref}",
        "downloads_url": "https://api.github.com/repos/SaiBarathR/personal-portfolio/downloads",
        "issues_url": "https://api.github.com/repos/SaiBarathR/personal-portfolio/issues{/number}",
        "pulls_url": "https://api.github.com/repos/SaiBarathR/personal-portfolio/pulls{/number}",
        "milestones_url": "https://api.github.com/repos/SaiBarathR/personal-portfolio/milestones{/number}",
        "notifications_url": "https://api.github.com/repos/SaiBarathR/personal-portfolio/notifications{?since,all,participating}",
        "labels_url": "https://api.github.com/repos/SaiBarathR/personal-portfolio/labels{/name}",
        "releases_url": "https://api.github.com/repos/SaiBarathR/personal-portfolio/releases{/id}",
        "deployments_url": "https://api.github.com/repos/SaiBarathR/personal-portfolio/deployments",
        "created_at": "2023-07-06T09:59:23Z",
        "updated_at": "2023-07-09T17:43:03Z",
        "pushed_at": "2023-07-08T23:04:57Z",
        "git_url": "git://github.com/SaiBarathR/personal-portfolio.git",
        "ssh_url": "git@github.com:SaiBarathR/personal-portfolio.git",
        "clone_url": "https://github.com/SaiBarathR/personal-portfolio.git",
        "svn_url": "https://github.com/SaiBarathR/personal-portfolio",
        "homepage": "https://saibarathr.netlify.app/",
        "size": 1656,
        "stargazers_count": 0,
        "watchers_count": 0,
        "language": "JavaScript",
        "has_issues": true,
        "has_projects": true,
        "has_downloads": true,
        "has_wiki": true,
        "has_pages": false,
        "has_discussions": false,
        "forks_count": 0,
        "mirror_url": null,
        "archived": false,
        "disabled": false,
        "open_issues_count": 0,
        "license": null,
        "allow_forking": true,
        "is_template": false,
        "web_commit_signoff_required": false,
        "topics": [
            "animation-css",
            "github-api",
            "nextjs",
            "react-server-components",
            "tailwind-css",
            "webpack5"
        ],
        "visibility": "public",
        "forks": 0,
        "open_issues": 0,
        "watchers": 0,
        "default_branch": "main"
    },
    {
        "id": 660360522,
        "node_id": "R_kgDOJ1xNSg",
        "name": "watch-together",
        "full_name": "SaiBarathR/watch-together",
        "private": false,
        "owner": {
            "login": "SaiBarathR",
            "id": 58382813,
            "node_id": "MDQ6VXNlcjU4MzgyODEz",
            "avatar_url": "https://avatars.githubusercontent.com/u/58382813?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/SaiBarathR",
            "html_url": "https://github.com/SaiBarathR",
            "followers_url": "https://api.github.com/users/SaiBarathR/followers",
            "following_url": "https://api.github.com/users/SaiBarathR/following{/other_user}",
            "gists_url": "https://api.github.com/users/SaiBarathR/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/SaiBarathR/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/SaiBarathR/subscriptions",
            "organizations_url": "https://api.github.com/users/SaiBarathR/orgs",
            "repos_url": "https://api.github.com/users/SaiBarathR/repos",
            "events_url": "https://api.github.com/users/SaiBarathR/events{/privacy}",
            "received_events_url": "https://api.github.com/users/SaiBarathR/received_events",
            "type": "User",
            "site_admin": false
        },
        "html_url": "https://github.com/SaiBarathR/watch-together",
        "description": "/*In Development learning in-depth about WebRTC */. Personal passion project. Use Case: Watch videos/movies together with your friends & family from any where in the world together using your local videos or any streaming service..",
        "fork": false,
        "url": "https://api.github.com/repos/SaiBarathR/watch-together",
        "forks_url": "https://api.github.com/repos/SaiBarathR/watch-together/forks",
        "keys_url": "https://api.github.com/repos/SaiBarathR/watch-together/keys{/key_id}",
        "collaborators_url": "https://api.github.com/repos/SaiBarathR/watch-together/collaborators{/collaborator}",
        "teams_url": "https://api.github.com/repos/SaiBarathR/watch-together/teams",
        "hooks_url": "https://api.github.com/repos/SaiBarathR/watch-together/hooks",
        "issue_events_url": "https://api.github.com/repos/SaiBarathR/watch-together/issues/events{/number}",
        "events_url": "https://api.github.com/repos/SaiBarathR/watch-together/events",
        "assignees_url": "https://api.github.com/repos/SaiBarathR/watch-together/assignees{/user}",
        "branches_url": "https://api.github.com/repos/SaiBarathR/watch-together/branches{/branch}",
        "tags_url": "https://api.github.com/repos/SaiBarathR/watch-together/tags",
        "blobs_url": "https://api.github.com/repos/SaiBarathR/watch-together/git/blobs{/sha}",
        "git_tags_url": "https://api.github.com/repos/SaiBarathR/watch-together/git/tags{/sha}",
        "git_refs_url": "https://api.github.com/repos/SaiBarathR/watch-together/git/refs{/sha}",
        "trees_url": "https://api.github.com/repos/SaiBarathR/watch-together/git/trees{/sha}",
        "statuses_url": "https://api.github.com/repos/SaiBarathR/watch-together/statuses/{sha}",
        "languages_url": "https://api.github.com/repos/SaiBarathR/watch-together/languages",
        "stargazers_url": "https://api.github.com/repos/SaiBarathR/watch-together/stargazers",
        "contributors_url": "https://api.github.com/repos/SaiBarathR/watch-together/contributors",
        "subscribers_url": "https://api.github.com/repos/SaiBarathR/watch-together/subscribers",
        "subscription_url": "https://api.github.com/repos/SaiBarathR/watch-together/subscription",
        "commits_url": "https://api.github.com/repos/SaiBarathR/watch-together/commits{/sha}",
        "git_commits_url": "https://api.github.com/repos/SaiBarathR/watch-together/git/commits{/sha}",
        "comments_url": "https://api.github.com/repos/SaiBarathR/watch-together/comments{/number}",
        "issue_comment_url": "https://api.github.com/repos/SaiBarathR/watch-together/issues/comments{/number}",
        "contents_url": "https://api.github.com/repos/SaiBarathR/watch-together/contents/{+path}",
        "compare_url": "https://api.github.com/repos/SaiBarathR/watch-together/compare/{base}...{head}",
        "merges_url": "https://api.github.com/repos/SaiBarathR/watch-together/merges",
        "archive_url": "https://api.github.com/repos/SaiBarathR/watch-together/{archive_format}{/ref}",
        "downloads_url": "https://api.github.com/repos/SaiBarathR/watch-together/downloads",
        "issues_url": "https://api.github.com/repos/SaiBarathR/watch-together/issues{/number}",
        "pulls_url": "https://api.github.com/repos/SaiBarathR/watch-together/pulls{/number}",
        "milestones_url": "https://api.github.com/repos/SaiBarathR/watch-together/milestones{/number}",
        "notifications_url": "https://api.github.com/repos/SaiBarathR/watch-together/notifications{?since,all,participating}",
        "labels_url": "https://api.github.com/repos/SaiBarathR/watch-together/labels{/name}",
        "releases_url": "https://api.github.com/repos/SaiBarathR/watch-together/releases{/id}",
        "deployments_url": "https://api.github.com/repos/SaiBarathR/watch-together/deployments",
        "created_at": "2023-06-29T20:46:48Z",
        "updated_at": "2023-07-09T17:32:51Z",
        "pushed_at": "2023-06-30T18:19:36Z",
        "git_url": "git://github.com/SaiBarathR/watch-together.git",
        "ssh_url": "git@github.com:SaiBarathR/watch-together.git",
        "clone_url": "https://github.com/SaiBarathR/watch-together.git",
        "svn_url": "https://github.com/SaiBarathR/watch-together",
        "homepage": "https://watch-together-firstphase.netlify.app/",
        "size": 732,
        "stargazers_count": 0,
        "watchers_count": 0,
        "language": "JavaScript",
        "has_issues": true,
        "has_projects": true,
        "has_downloads": true,
        "has_wiki": true,
        "has_pages": false,
        "has_discussions": false,
        "forks_count": 0,
        "mirror_url": null,
        "archived": false,
        "disabled": false,
        "open_issues_count": 0,
        "license": null,
        "allow_forking": true,
        "is_template": false,
        "web_commit_signoff_required": false,
        "topics": [
            "babel",
            "react",
            "spring-boot",
            "webpack5",
            "webrtc-video",
            "websocket"
        ],
        "visibility": "public",
        "forks": 0,
        "open_issues": 0,
        "watchers": 0,
        "default_branch": "firstPhase"
    },
    {
        "id": 662942402,
        "node_id": "R_kgDOJ4Oywg",
        "name": "email-newsletter-nodesJs-postgresql",
        "full_name": "SaiBarathR/email-newsletter-nodesJs-postgresql",
        "private": false,
        "owner": {
            "login": "SaiBarathR",
            "id": 58382813,
            "node_id": "MDQ6VXNlcjU4MzgyODEz",
            "avatar_url": "https://avatars.githubusercontent.com/u/58382813?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/SaiBarathR",
            "html_url": "https://github.com/SaiBarathR",
            "followers_url": "https://api.github.com/users/SaiBarathR/followers",
            "following_url": "https://api.github.com/users/SaiBarathR/following{/other_user}",
            "gists_url": "https://api.github.com/users/SaiBarathR/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/SaiBarathR/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/SaiBarathR/subscriptions",
            "organizations_url": "https://api.github.com/users/SaiBarathR/orgs",
            "repos_url": "https://api.github.com/users/SaiBarathR/repos",
            "events_url": "https://api.github.com/users/SaiBarathR/events{/privacy}",
            "received_events_url": "https://api.github.com/users/SaiBarathR/received_events",
            "type": "User",
            "site_admin": false
        },
        "html_url": "https://github.com/SaiBarathR/email-newsletter-nodesJs-postgresql",
        "description": "Going through this code you can learn how to create a email newsletter using Node.js and Postgresql for bulk email scheduling jobs. Edit the config file according to your backend needs. ",
        "fork": false,
        "url": "https://api.github.com/repos/SaiBarathR/email-newsletter-nodesJs-postgresql",
        "forks_url": "https://api.github.com/repos/SaiBarathR/email-newsletter-nodesJs-postgresql/forks",
        "keys_url": "https://api.github.com/repos/SaiBarathR/email-newsletter-nodesJs-postgresql/keys{/key_id}",
        "collaborators_url": "https://api.github.com/repos/SaiBarathR/email-newsletter-nodesJs-postgresql/collaborators{/collaborator}",
        "teams_url": "https://api.github.com/repos/SaiBarathR/email-newsletter-nodesJs-postgresql/teams",
        "hooks_url": "https://api.github.com/repos/SaiBarathR/email-newsletter-nodesJs-postgresql/hooks",
        "issue_events_url": "https://api.github.com/repos/SaiBarathR/email-newsletter-nodesJs-postgresql/issues/events{/number}",
        "events_url": "https://api.github.com/repos/SaiBarathR/email-newsletter-nodesJs-postgresql/events",
        "assignees_url": "https://api.github.com/repos/SaiBarathR/email-newsletter-nodesJs-postgresql/assignees{/user}",
        "branches_url": "https://api.github.com/repos/SaiBarathR/email-newsletter-nodesJs-postgresql/branches{/branch}",
        "tags_url": "https://api.github.com/repos/SaiBarathR/email-newsletter-nodesJs-postgresql/tags",
        "blobs_url": "https://api.github.com/repos/SaiBarathR/email-newsletter-nodesJs-postgresql/git/blobs{/sha}",
        "git_tags_url": "https://api.github.com/repos/SaiBarathR/email-newsletter-nodesJs-postgresql/git/tags{/sha}",
        "git_refs_url": "https://api.github.com/repos/SaiBarathR/email-newsletter-nodesJs-postgresql/git/refs{/sha}",
        "trees_url": "https://api.github.com/repos/SaiBarathR/email-newsletter-nodesJs-postgresql/git/trees{/sha}",
        "statuses_url": "https://api.github.com/repos/SaiBarathR/email-newsletter-nodesJs-postgresql/statuses/{sha}",
        "languages_url": "https://api.github.com/repos/SaiBarathR/email-newsletter-nodesJs-postgresql/languages",
        "stargazers_url": "https://api.github.com/repos/SaiBarathR/email-newsletter-nodesJs-postgresql/stargazers",
        "contributors_url": "https://api.github.com/repos/SaiBarathR/email-newsletter-nodesJs-postgresql/contributors",
        "subscribers_url": "https://api.github.com/repos/SaiBarathR/email-newsletter-nodesJs-postgresql/subscribers",
        "subscription_url": "https://api.github.com/repos/SaiBarathR/email-newsletter-nodesJs-postgresql/subscription",
        "commits_url": "https://api.github.com/repos/SaiBarathR/email-newsletter-nodesJs-postgresql/commits{/sha}",
        "git_commits_url": "https://api.github.com/repos/SaiBarathR/email-newsletter-nodesJs-postgresql/git/commits{/sha}",
        "comments_url": "https://api.github.com/repos/SaiBarathR/email-newsletter-nodesJs-postgresql/comments{/number}",
        "issue_comment_url": "https://api.github.com/repos/SaiBarathR/email-newsletter-nodesJs-postgresql/issues/comments{/number}",
        "contents_url": "https://api.github.com/repos/SaiBarathR/email-newsletter-nodesJs-postgresql/contents/{+path}",
        "compare_url": "https://api.github.com/repos/SaiBarathR/email-newsletter-nodesJs-postgresql/compare/{base}...{head}",
        "merges_url": "https://api.github.com/repos/SaiBarathR/email-newsletter-nodesJs-postgresql/merges",
        "archive_url": "https://api.github.com/repos/SaiBarathR/email-newsletter-nodesJs-postgresql/{archive_format}{/ref}",
        "downloads_url": "https://api.github.com/repos/SaiBarathR/email-newsletter-nodesJs-postgresql/downloads",
        "issues_url": "https://api.github.com/repos/SaiBarathR/email-newsletter-nodesJs-postgresql/issues{/number}",
        "pulls_url": "https://api.github.com/repos/SaiBarathR/email-newsletter-nodesJs-postgresql/pulls{/number}",
        "milestones_url": "https://api.github.com/repos/SaiBarathR/email-newsletter-nodesJs-postgresql/milestones{/number}",
        "notifications_url": "https://api.github.com/repos/SaiBarathR/email-newsletter-nodesJs-postgresql/notifications{?since,all,participating}",
        "labels_url": "https://api.github.com/repos/SaiBarathR/email-newsletter-nodesJs-postgresql/labels{/name}",
        "releases_url": "https://api.github.com/repos/SaiBarathR/email-newsletter-nodesJs-postgresql/releases{/id}",
        "deployments_url": "https://api.github.com/repos/SaiBarathR/email-newsletter-nodesJs-postgresql/deployments",
        "created_at": "2023-07-06T08:09:30Z",
        "updated_at": "2023-07-09T17:26:28Z",
        "pushed_at": "2023-07-06T09:40:15Z",
        "git_url": "git://github.com/SaiBarathR/email-newsletter-nodesJs-postgresql.git",
        "ssh_url": "git@github.com:SaiBarathR/email-newsletter-nodesJs-postgresql.git",
        "clone_url": "https://github.com/SaiBarathR/email-newsletter-nodesJs-postgresql.git",
        "svn_url": "https://github.com/SaiBarathR/email-newsletter-nodesJs-postgresql",
        "homepage": "",
        "size": 1287,
        "stargazers_count": 0,
        "watchers_count": 0,
        "language": "JavaScript",
        "has_issues": true,
        "has_projects": true,
        "has_downloads": true,
        "has_wiki": true,
        "has_pages": false,
        "has_discussions": false,
        "forks_count": 0,
        "mirror_url": null,
        "archived": false,
        "disabled": false,
        "open_issues_count": 0,
        "license": {
            "key": "mit",
            "name": "MIT License",
            "spdx_id": "MIT",
            "url": "https://api.github.com/licenses/mit",
            "node_id": "MDc6TGljZW5zZTEz"
        },
        "allow_forking": true,
        "is_template": false,
        "web_commit_signoff_required": false,
        "topics": [
            "express-js",
            "node-js",
            "nodemailer",
            "postgresql",
            "rest-api",
            "sql"
        ],
        "visibility": "public",
        "forks": 0,
        "open_issues": 0,
        "watchers": 0,
        "default_branch": "main"
    },
    {
        "id": 634502967,
        "node_id": "R_kgDOJdG_Nw",
        "name": "service-worker-starter-code",
        "full_name": "SaiBarathR/service-worker-starter-code",
        "private": false,
        "owner": {
            "login": "SaiBarathR",
            "id": 58382813,
            "node_id": "MDQ6VXNlcjU4MzgyODEz",
            "avatar_url": "https://avatars.githubusercontent.com/u/58382813?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/SaiBarathR",
            "html_url": "https://github.com/SaiBarathR",
            "followers_url": "https://api.github.com/users/SaiBarathR/followers",
            "following_url": "https://api.github.com/users/SaiBarathR/following{/other_user}",
            "gists_url": "https://api.github.com/users/SaiBarathR/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/SaiBarathR/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/SaiBarathR/subscriptions",
            "organizations_url": "https://api.github.com/users/SaiBarathR/orgs",
            "repos_url": "https://api.github.com/users/SaiBarathR/repos",
            "events_url": "https://api.github.com/users/SaiBarathR/events{/privacy}",
            "received_events_url": "https://api.github.com/users/SaiBarathR/received_events",
            "type": "User",
            "site_admin": false
        },
        "html_url": "https://github.com/SaiBarathR/service-worker-starter-code",
        "description": "Take a peep into this Service Worker stater code which i have created to implement notifications in any web app.",
        "fork": false,
        "url": "https://api.github.com/repos/SaiBarathR/service-worker-starter-code",
        "forks_url": "https://api.github.com/repos/SaiBarathR/service-worker-starter-code/forks",
        "keys_url": "https://api.github.com/repos/SaiBarathR/service-worker-starter-code/keys{/key_id}",
        "collaborators_url": "https://api.github.com/repos/SaiBarathR/service-worker-starter-code/collaborators{/collaborator}",
        "teams_url": "https://api.github.com/repos/SaiBarathR/service-worker-starter-code/teams",
        "hooks_url": "https://api.github.com/repos/SaiBarathR/service-worker-starter-code/hooks",
        "issue_events_url": "https://api.github.com/repos/SaiBarathR/service-worker-starter-code/issues/events{/number}",
        "events_url": "https://api.github.com/repos/SaiBarathR/service-worker-starter-code/events",
        "assignees_url": "https://api.github.com/repos/SaiBarathR/service-worker-starter-code/assignees{/user}",
        "branches_url": "https://api.github.com/repos/SaiBarathR/service-worker-starter-code/branches{/branch}",
        "tags_url": "https://api.github.com/repos/SaiBarathR/service-worker-starter-code/tags",
        "blobs_url": "https://api.github.com/repos/SaiBarathR/service-worker-starter-code/git/blobs{/sha}",
        "git_tags_url": "https://api.github.com/repos/SaiBarathR/service-worker-starter-code/git/tags{/sha}",
        "git_refs_url": "https://api.github.com/repos/SaiBarathR/service-worker-starter-code/git/refs{/sha}",
        "trees_url": "https://api.github.com/repos/SaiBarathR/service-worker-starter-code/git/trees{/sha}",
        "statuses_url": "https://api.github.com/repos/SaiBarathR/service-worker-starter-code/statuses/{sha}",
        "languages_url": "https://api.github.com/repos/SaiBarathR/service-worker-starter-code/languages",
        "stargazers_url": "https://api.github.com/repos/SaiBarathR/service-worker-starter-code/stargazers",
        "contributors_url": "https://api.github.com/repos/SaiBarathR/service-worker-starter-code/contributors",
        "subscribers_url": "https://api.github.com/repos/SaiBarathR/service-worker-starter-code/subscribers",
        "subscription_url": "https://api.github.com/repos/SaiBarathR/service-worker-starter-code/subscription",
        "commits_url": "https://api.github.com/repos/SaiBarathR/service-worker-starter-code/commits{/sha}",
        "git_commits_url": "https://api.github.com/repos/SaiBarathR/service-worker-starter-code/git/commits{/sha}",
        "comments_url": "https://api.github.com/repos/SaiBarathR/service-worker-starter-code/comments{/number}",
        "issue_comment_url": "https://api.github.com/repos/SaiBarathR/service-worker-starter-code/issues/comments{/number}",
        "contents_url": "https://api.github.com/repos/SaiBarathR/service-worker-starter-code/contents/{+path}",
        "compare_url": "https://api.github.com/repos/SaiBarathR/service-worker-starter-code/compare/{base}...{head}",
        "merges_url": "https://api.github.com/repos/SaiBarathR/service-worker-starter-code/merges",
        "archive_url": "https://api.github.com/repos/SaiBarathR/service-worker-starter-code/{archive_format}{/ref}",
        "downloads_url": "https://api.github.com/repos/SaiBarathR/service-worker-starter-code/downloads",
        "issues_url": "https://api.github.com/repos/SaiBarathR/service-worker-starter-code/issues{/number}",
        "pulls_url": "https://api.github.com/repos/SaiBarathR/service-worker-starter-code/pulls{/number}",
        "milestones_url": "https://api.github.com/repos/SaiBarathR/service-worker-starter-code/milestones{/number}",
        "notifications_url": "https://api.github.com/repos/SaiBarathR/service-worker-starter-code/notifications{?since,all,participating}",
        "labels_url": "https://api.github.com/repos/SaiBarathR/service-worker-starter-code/labels{/name}",
        "releases_url": "https://api.github.com/repos/SaiBarathR/service-worker-starter-code/releases{/id}",
        "deployments_url": "https://api.github.com/repos/SaiBarathR/service-worker-starter-code/deployments",
        "created_at": "2023-04-30T10:41:47Z",
        "updated_at": "2023-07-09T17:25:16Z",
        "pushed_at": "2023-06-30T18:25:19Z",
        "git_url": "git://github.com/SaiBarathR/service-worker-starter-code.git",
        "ssh_url": "git@github.com:SaiBarathR/service-worker-starter-code.git",
        "clone_url": "https://github.com/SaiBarathR/service-worker-starter-code.git",
        "svn_url": "https://github.com/SaiBarathR/service-worker-starter-code",
        "homepage": "https://sw-provider.netlify.app/",
        "size": 400,
        "stargazers_count": 1,
        "watchers_count": 1,
        "language": "JavaScript",
        "has_issues": true,
        "has_projects": true,
        "has_downloads": true,
        "has_wiki": true,
        "has_pages": false,
        "has_discussions": true,
        "forks_count": 0,
        "mirror_url": null,
        "archived": false,
        "disabled": false,
        "open_issues_count": 0,
        "license": null,
        "allow_forking": true,
        "is_template": false,
        "web_commit_signoff_required": false,
        "topics": [
            "animation-css",
            "react",
            "service-worker",
            "web-api",
            "web-notifcations-api"
        ],
        "visibility": "public",
        "forks": 0,
        "open_issues": 0,
        "watchers": 1,
        "default_branch": "main"
    },
    {
        "id": 663978008,
        "node_id": "R_kgDOJ5OAGA",
        "name": "react-components",
        "full_name": "SaiBarathR/react-components",
        "private": false,
        "owner": {
            "login": "SaiBarathR",
            "id": 58382813,
            "node_id": "MDQ6VXNlcjU4MzgyODEz",
            "avatar_url": "https://avatars.githubusercontent.com/u/58382813?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/SaiBarathR",
            "html_url": "https://github.com/SaiBarathR",
            "followers_url": "https://api.github.com/users/SaiBarathR/followers",
            "following_url": "https://api.github.com/users/SaiBarathR/following{/other_user}",
            "gists_url": "https://api.github.com/users/SaiBarathR/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/SaiBarathR/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/SaiBarathR/subscriptions",
            "organizations_url": "https://api.github.com/users/SaiBarathR/orgs",
            "repos_url": "https://api.github.com/users/SaiBarathR/repos",
            "events_url": "https://api.github.com/users/SaiBarathR/events{/privacy}",
            "received_events_url": "https://api.github.com/users/SaiBarathR/received_events",
            "type": "User",
            "site_admin": false
        },
        "html_url": "https://github.com/SaiBarathR/react-components",
        "description": "In this repo I am adding all the reusable react components whenever i create them.",
        "fork": false,
        "url": "https://api.github.com/repos/SaiBarathR/react-components",
        "forks_url": "https://api.github.com/repos/SaiBarathR/react-components/forks",
        "keys_url": "https://api.github.com/repos/SaiBarathR/react-components/keys{/key_id}",
        "collaborators_url": "https://api.github.com/repos/SaiBarathR/react-components/collaborators{/collaborator}",
        "teams_url": "https://api.github.com/repos/SaiBarathR/react-components/teams",
        "hooks_url": "https://api.github.com/repos/SaiBarathR/react-components/hooks",
        "issue_events_url": "https://api.github.com/repos/SaiBarathR/react-components/issues/events{/number}",
        "events_url": "https://api.github.com/repos/SaiBarathR/react-components/events",
        "assignees_url": "https://api.github.com/repos/SaiBarathR/react-components/assignees{/user}",
        "branches_url": "https://api.github.com/repos/SaiBarathR/react-components/branches{/branch}",
        "tags_url": "https://api.github.com/repos/SaiBarathR/react-components/tags",
        "blobs_url": "https://api.github.com/repos/SaiBarathR/react-components/git/blobs{/sha}",
        "git_tags_url": "https://api.github.com/repos/SaiBarathR/react-components/git/tags{/sha}",
        "git_refs_url": "https://api.github.com/repos/SaiBarathR/react-components/git/refs{/sha}",
        "trees_url": "https://api.github.com/repos/SaiBarathR/react-components/git/trees{/sha}",
        "statuses_url": "https://api.github.com/repos/SaiBarathR/react-components/statuses/{sha}",
        "languages_url": "https://api.github.com/repos/SaiBarathR/react-components/languages",
        "stargazers_url": "https://api.github.com/repos/SaiBarathR/react-components/stargazers",
        "contributors_url": "https://api.github.com/repos/SaiBarathR/react-components/contributors",
        "subscribers_url": "https://api.github.com/repos/SaiBarathR/react-components/subscribers",
        "subscription_url": "https://api.github.com/repos/SaiBarathR/react-components/subscription",
        "commits_url": "https://api.github.com/repos/SaiBarathR/react-components/commits{/sha}",
        "git_commits_url": "https://api.github.com/repos/SaiBarathR/react-components/git/commits{/sha}",
        "comments_url": "https://api.github.com/repos/SaiBarathR/react-components/comments{/number}",
        "issue_comment_url": "https://api.github.com/repos/SaiBarathR/react-components/issues/comments{/number}",
        "contents_url": "https://api.github.com/repos/SaiBarathR/react-components/contents/{+path}",
        "compare_url": "https://api.github.com/repos/SaiBarathR/react-components/compare/{base}...{head}",
        "merges_url": "https://api.github.com/repos/SaiBarathR/react-components/merges",
        "archive_url": "https://api.github.com/repos/SaiBarathR/react-components/{archive_format}{/ref}",
        "downloads_url": "https://api.github.com/repos/SaiBarathR/react-components/downloads",
        "issues_url": "https://api.github.com/repos/SaiBarathR/react-components/issues{/number}",
        "pulls_url": "https://api.github.com/repos/SaiBarathR/react-components/pulls{/number}",
        "milestones_url": "https://api.github.com/repos/SaiBarathR/react-components/milestones{/number}",
        "notifications_url": "https://api.github.com/repos/SaiBarathR/react-components/notifications{?since,all,participating}",
        "labels_url": "https://api.github.com/repos/SaiBarathR/react-components/labels{/name}",
        "releases_url": "https://api.github.com/repos/SaiBarathR/react-components/releases{/id}",
        "deployments_url": "https://api.github.com/repos/SaiBarathR/react-components/deployments",
        "created_at": "2023-07-08T15:34:28Z",
        "updated_at": "2023-07-09T17:22:57Z",
        "pushed_at": "2023-07-08T16:47:04Z",
        "git_url": "git://github.com/SaiBarathR/react-components.git",
        "ssh_url": "git@github.com:SaiBarathR/react-components.git",
        "clone_url": "https://github.com/SaiBarathR/react-components.git",
        "svn_url": "https://github.com/SaiBarathR/react-components",
        "homepage": "",
        "size": 10,
        "stargazers_count": 0,
        "watchers_count": 0,
        "language": "JavaScript",
        "has_issues": true,
        "has_projects": true,
        "has_downloads": true,
        "has_wiki": true,
        "has_pages": false,
        "has_discussions": false,
        "forks_count": 0,
        "mirror_url": null,
        "archived": false,
        "disabled": false,
        "open_issues_count": 0,
        "license": {
            "key": "mit",
            "name": "MIT License",
            "spdx_id": "MIT",
            "url": "https://api.github.com/licenses/mit",
            "node_id": "MDc6TGljZW5zZTEz"
        },
        "allow_forking": true,
        "is_template": false,
        "web_commit_signoff_required": false,
        "topics": [
            "animation-css",
            "javascript-library",
            "reactjs",
            "sass",
            "web-api",
            "webpack"
        ],
        "visibility": "public",
        "forks": 0,
        "open_issues": 0,
        "watchers": 0,
        "default_branch": "main"
    },
    {
        "id": 335593708,
        "node_id": "MDEwOlJlcG9zaXRvcnkzMzU1OTM3MDg=",
        "name": "Movie-Bot",
        "full_name": "SaiBarathR/Movie-Bot",
        "private": false,
        "owner": {
            "login": "SaiBarathR",
            "id": 58382813,
            "node_id": "MDQ6VXNlcjU4MzgyODEz",
            "avatar_url": "https://avatars.githubusercontent.com/u/58382813?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/SaiBarathR",
            "html_url": "https://github.com/SaiBarathR",
            "followers_url": "https://api.github.com/users/SaiBarathR/followers",
            "following_url": "https://api.github.com/users/SaiBarathR/following{/other_user}",
            "gists_url": "https://api.github.com/users/SaiBarathR/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/SaiBarathR/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/SaiBarathR/subscriptions",
            "organizations_url": "https://api.github.com/users/SaiBarathR/orgs",
            "repos_url": "https://api.github.com/users/SaiBarathR/repos",
            "events_url": "https://api.github.com/users/SaiBarathR/events{/privacy}",
            "received_events_url": "https://api.github.com/users/SaiBarathR/received_events",
            "type": "User",
            "site_admin": false
        },
        "html_url": "https://github.com/SaiBarathR/Movie-Bot",
        "description": "Created this telegram bot for my telegram channel users to lookup the details of movie quickly without leaving the telegram app..",
        "fork": false,
        "url": "https://api.github.com/repos/SaiBarathR/Movie-Bot",
        "forks_url": "https://api.github.com/repos/SaiBarathR/Movie-Bot/forks",
        "keys_url": "https://api.github.com/repos/SaiBarathR/Movie-Bot/keys{/key_id}",
        "collaborators_url": "https://api.github.com/repos/SaiBarathR/Movie-Bot/collaborators{/collaborator}",
        "teams_url": "https://api.github.com/repos/SaiBarathR/Movie-Bot/teams",
        "hooks_url": "https://api.github.com/repos/SaiBarathR/Movie-Bot/hooks",
        "issue_events_url": "https://api.github.com/repos/SaiBarathR/Movie-Bot/issues/events{/number}",
        "events_url": "https://api.github.com/repos/SaiBarathR/Movie-Bot/events",
        "assignees_url": "https://api.github.com/repos/SaiBarathR/Movie-Bot/assignees{/user}",
        "branches_url": "https://api.github.com/repos/SaiBarathR/Movie-Bot/branches{/branch}",
        "tags_url": "https://api.github.com/repos/SaiBarathR/Movie-Bot/tags",
        "blobs_url": "https://api.github.com/repos/SaiBarathR/Movie-Bot/git/blobs{/sha}",
        "git_tags_url": "https://api.github.com/repos/SaiBarathR/Movie-Bot/git/tags{/sha}",
        "git_refs_url": "https://api.github.com/repos/SaiBarathR/Movie-Bot/git/refs{/sha}",
        "trees_url": "https://api.github.com/repos/SaiBarathR/Movie-Bot/git/trees{/sha}",
        "statuses_url": "https://api.github.com/repos/SaiBarathR/Movie-Bot/statuses/{sha}",
        "languages_url": "https://api.github.com/repos/SaiBarathR/Movie-Bot/languages",
        "stargazers_url": "https://api.github.com/repos/SaiBarathR/Movie-Bot/stargazers",
        "contributors_url": "https://api.github.com/repos/SaiBarathR/Movie-Bot/contributors",
        "subscribers_url": "https://api.github.com/repos/SaiBarathR/Movie-Bot/subscribers",
        "subscription_url": "https://api.github.com/repos/SaiBarathR/Movie-Bot/subscription",
        "commits_url": "https://api.github.com/repos/SaiBarathR/Movie-Bot/commits{/sha}",
        "git_commits_url": "https://api.github.com/repos/SaiBarathR/Movie-Bot/git/commits{/sha}",
        "comments_url": "https://api.github.com/repos/SaiBarathR/Movie-Bot/comments{/number}",
        "issue_comment_url": "https://api.github.com/repos/SaiBarathR/Movie-Bot/issues/comments{/number}",
        "contents_url": "https://api.github.com/repos/SaiBarathR/Movie-Bot/contents/{+path}",
        "compare_url": "https://api.github.com/repos/SaiBarathR/Movie-Bot/compare/{base}...{head}",
        "merges_url": "https://api.github.com/repos/SaiBarathR/Movie-Bot/merges",
        "archive_url": "https://api.github.com/repos/SaiBarathR/Movie-Bot/{archive_format}{/ref}",
        "downloads_url": "https://api.github.com/repos/SaiBarathR/Movie-Bot/downloads",
        "issues_url": "https://api.github.com/repos/SaiBarathR/Movie-Bot/issues{/number}",
        "pulls_url": "https://api.github.com/repos/SaiBarathR/Movie-Bot/pulls{/number}",
        "milestones_url": "https://api.github.com/repos/SaiBarathR/Movie-Bot/milestones{/number}",
        "notifications_url": "https://api.github.com/repos/SaiBarathR/Movie-Bot/notifications{?since,all,participating}",
        "labels_url": "https://api.github.com/repos/SaiBarathR/Movie-Bot/labels{/name}",
        "releases_url": "https://api.github.com/repos/SaiBarathR/Movie-Bot/releases{/id}",
        "deployments_url": "https://api.github.com/repos/SaiBarathR/Movie-Bot/deployments",
        "created_at": "2021-02-03T10:53:11Z",
        "updated_at": "2023-07-09T17:16:57Z",
        "pushed_at": "2021-02-03T10:53:49Z",
        "git_url": "git://github.com/SaiBarathR/Movie-Bot.git",
        "ssh_url": "git@github.com:SaiBarathR/Movie-Bot.git",
        "clone_url": "https://github.com/SaiBarathR/Movie-Bot.git",
        "svn_url": "https://github.com/SaiBarathR/Movie-Bot",
        "homepage": "",
        "size": 9,
        "stargazers_count": 1,
        "watchers_count": 1,
        "language": "Python",
        "has_issues": true,
        "has_projects": true,
        "has_downloads": true,
        "has_wiki": true,
        "has_pages": false,
        "has_discussions": false,
        "forks_count": 0,
        "mirror_url": null,
        "archived": false,
        "disabled": false,
        "open_issues_count": 0,
        "license": null,
        "allow_forking": true,
        "is_template": false,
        "web_commit_signoff_required": false,
        "topics": [
            "pyscript",
            "pysqlite3",
            "python",
            "telegram-bot"
        ],
        "visibility": "public",
        "forks": 0,
        "open_issues": 0,
        "watchers": 1,
        "default_branch": "master"
    },
    {
        "id": 335594049,
        "node_id": "MDEwOlJlcG9zaXRvcnkzMzU1OTQwNDk=",
        "name": "Water-Jug-Problem",
        "full_name": "SaiBarathR/Water-Jug-Problem",
        "private": false,
        "owner": {
            "login": "SaiBarathR",
            "id": 58382813,
            "node_id": "MDQ6VXNlcjU4MzgyODEz",
            "avatar_url": "https://avatars.githubusercontent.com/u/58382813?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/SaiBarathR",
            "html_url": "https://github.com/SaiBarathR",
            "followers_url": "https://api.github.com/users/SaiBarathR/followers",
            "following_url": "https://api.github.com/users/SaiBarathR/following{/other_user}",
            "gists_url": "https://api.github.com/users/SaiBarathR/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/SaiBarathR/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/SaiBarathR/subscriptions",
            "organizations_url": "https://api.github.com/users/SaiBarathR/orgs",
            "repos_url": "https://api.github.com/users/SaiBarathR/repos",
            "events_url": "https://api.github.com/users/SaiBarathR/events{/privacy}",
            "received_events_url": "https://api.github.com/users/SaiBarathR/received_events",
            "type": "User",
            "site_admin": false
        },
        "html_url": "https://github.com/SaiBarathR/Water-Jug-Problem",
        "description": "Added this new and efficient solution to solve water jug problem.",
        "fork": false,
        "url": "https://api.github.com/repos/SaiBarathR/Water-Jug-Problem",
        "forks_url": "https://api.github.com/repos/SaiBarathR/Water-Jug-Problem/forks",
        "keys_url": "https://api.github.com/repos/SaiBarathR/Water-Jug-Problem/keys{/key_id}",
        "collaborators_url": "https://api.github.com/repos/SaiBarathR/Water-Jug-Problem/collaborators{/collaborator}",
        "teams_url": "https://api.github.com/repos/SaiBarathR/Water-Jug-Problem/teams",
        "hooks_url": "https://api.github.com/repos/SaiBarathR/Water-Jug-Problem/hooks",
        "issue_events_url": "https://api.github.com/repos/SaiBarathR/Water-Jug-Problem/issues/events{/number}",
        "events_url": "https://api.github.com/repos/SaiBarathR/Water-Jug-Problem/events",
        "assignees_url": "https://api.github.com/repos/SaiBarathR/Water-Jug-Problem/assignees{/user}",
        "branches_url": "https://api.github.com/repos/SaiBarathR/Water-Jug-Problem/branches{/branch}",
        "tags_url": "https://api.github.com/repos/SaiBarathR/Water-Jug-Problem/tags",
        "blobs_url": "https://api.github.com/repos/SaiBarathR/Water-Jug-Problem/git/blobs{/sha}",
        "git_tags_url": "https://api.github.com/repos/SaiBarathR/Water-Jug-Problem/git/tags{/sha}",
        "git_refs_url": "https://api.github.com/repos/SaiBarathR/Water-Jug-Problem/git/refs{/sha}",
        "trees_url": "https://api.github.com/repos/SaiBarathR/Water-Jug-Problem/git/trees{/sha}",
        "statuses_url": "https://api.github.com/repos/SaiBarathR/Water-Jug-Problem/statuses/{sha}",
        "languages_url": "https://api.github.com/repos/SaiBarathR/Water-Jug-Problem/languages",
        "stargazers_url": "https://api.github.com/repos/SaiBarathR/Water-Jug-Problem/stargazers",
        "contributors_url": "https://api.github.com/repos/SaiBarathR/Water-Jug-Problem/contributors",
        "subscribers_url": "https://api.github.com/repos/SaiBarathR/Water-Jug-Problem/subscribers",
        "subscription_url": "https://api.github.com/repos/SaiBarathR/Water-Jug-Problem/subscription",
        "commits_url": "https://api.github.com/repos/SaiBarathR/Water-Jug-Problem/commits{/sha}",
        "git_commits_url": "https://api.github.com/repos/SaiBarathR/Water-Jug-Problem/git/commits{/sha}",
        "comments_url": "https://api.github.com/repos/SaiBarathR/Water-Jug-Problem/comments{/number}",
        "issue_comment_url": "https://api.github.com/repos/SaiBarathR/Water-Jug-Problem/issues/comments{/number}",
        "contents_url": "https://api.github.com/repos/SaiBarathR/Water-Jug-Problem/contents/{+path}",
        "compare_url": "https://api.github.com/repos/SaiBarathR/Water-Jug-Problem/compare/{base}...{head}",
        "merges_url": "https://api.github.com/repos/SaiBarathR/Water-Jug-Problem/merges",
        "archive_url": "https://api.github.com/repos/SaiBarathR/Water-Jug-Problem/{archive_format}{/ref}",
        "downloads_url": "https://api.github.com/repos/SaiBarathR/Water-Jug-Problem/downloads",
        "issues_url": "https://api.github.com/repos/SaiBarathR/Water-Jug-Problem/issues{/number}",
        "pulls_url": "https://api.github.com/repos/SaiBarathR/Water-Jug-Problem/pulls{/number}",
        "milestones_url": "https://api.github.com/repos/SaiBarathR/Water-Jug-Problem/milestones{/number}",
        "notifications_url": "https://api.github.com/repos/SaiBarathR/Water-Jug-Problem/notifications{?since,all,participating}",
        "labels_url": "https://api.github.com/repos/SaiBarathR/Water-Jug-Problem/labels{/name}",
        "releases_url": "https://api.github.com/repos/SaiBarathR/Water-Jug-Problem/releases{/id}",
        "deployments_url": "https://api.github.com/repos/SaiBarathR/Water-Jug-Problem/deployments",
        "created_at": "2021-02-03T10:54:39Z",
        "updated_at": "2023-07-09T17:16:28Z",
        "pushed_at": "2021-02-03T11:04:56Z",
        "git_url": "git://github.com/SaiBarathR/Water-Jug-Problem.git",
        "ssh_url": "git@github.com:SaiBarathR/Water-Jug-Problem.git",
        "clone_url": "https://github.com/SaiBarathR/Water-Jug-Problem.git",
        "svn_url": "https://github.com/SaiBarathR/Water-Jug-Problem",
        "homepage": "",
        "size": 1,
        "stargazers_count": 1,
        "watchers_count": 1,
        "language": "Python",
        "has_issues": true,
        "has_projects": true,
        "has_downloads": true,
        "has_wiki": true,
        "has_pages": false,
        "has_discussions": false,
        "forks_count": 0,
        "mirror_url": null,
        "archived": false,
        "disabled": false,
        "open_issues_count": 0,
        "license": null,
        "allow_forking": true,
        "is_template": false,
        "web_commit_signoff_required": false,
        "topics": [
            "python",
            "waterjugproblem"
        ],
        "visibility": "public",
        "forks": 0,
        "open_issues": 0,
        "watchers": 1,
        "default_branch": "main"
    },
    {
        "id": 335592835,
        "node_id": "MDEwOlJlcG9zaXRvcnkzMzU1OTI4MzU=",
        "name": "To-Do",
        "full_name": "SaiBarathR/To-Do",
        "private": false,
        "owner": {
            "login": "SaiBarathR",
            "id": 58382813,
            "node_id": "MDQ6VXNlcjU4MzgyODEz",
            "avatar_url": "https://avatars.githubusercontent.com/u/58382813?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/SaiBarathR",
            "html_url": "https://github.com/SaiBarathR",
            "followers_url": "https://api.github.com/users/SaiBarathR/followers",
            "following_url": "https://api.github.com/users/SaiBarathR/following{/other_user}",
            "gists_url": "https://api.github.com/users/SaiBarathR/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/SaiBarathR/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/SaiBarathR/subscriptions",
            "organizations_url": "https://api.github.com/users/SaiBarathR/orgs",
            "repos_url": "https://api.github.com/users/SaiBarathR/repos",
            "events_url": "https://api.github.com/users/SaiBarathR/events{/privacy}",
            "received_events_url": "https://api.github.com/users/SaiBarathR/received_events",
            "type": "User",
            "site_admin": false
        },
        "html_url": "https://github.com/SaiBarathR/To-Do",
        "description": "Created this simple python todo app to explore more python libraries.",
        "fork": false,
        "url": "https://api.github.com/repos/SaiBarathR/To-Do",
        "forks_url": "https://api.github.com/repos/SaiBarathR/To-Do/forks",
        "keys_url": "https://api.github.com/repos/SaiBarathR/To-Do/keys{/key_id}",
        "collaborators_url": "https://api.github.com/repos/SaiBarathR/To-Do/collaborators{/collaborator}",
        "teams_url": "https://api.github.com/repos/SaiBarathR/To-Do/teams",
        "hooks_url": "https://api.github.com/repos/SaiBarathR/To-Do/hooks",
        "issue_events_url": "https://api.github.com/repos/SaiBarathR/To-Do/issues/events{/number}",
        "events_url": "https://api.github.com/repos/SaiBarathR/To-Do/events",
        "assignees_url": "https://api.github.com/repos/SaiBarathR/To-Do/assignees{/user}",
        "branches_url": "https://api.github.com/repos/SaiBarathR/To-Do/branches{/branch}",
        "tags_url": "https://api.github.com/repos/SaiBarathR/To-Do/tags",
        "blobs_url": "https://api.github.com/repos/SaiBarathR/To-Do/git/blobs{/sha}",
        "git_tags_url": "https://api.github.com/repos/SaiBarathR/To-Do/git/tags{/sha}",
        "git_refs_url": "https://api.github.com/repos/SaiBarathR/To-Do/git/refs{/sha}",
        "trees_url": "https://api.github.com/repos/SaiBarathR/To-Do/git/trees{/sha}",
        "statuses_url": "https://api.github.com/repos/SaiBarathR/To-Do/statuses/{sha}",
        "languages_url": "https://api.github.com/repos/SaiBarathR/To-Do/languages",
        "stargazers_url": "https://api.github.com/repos/SaiBarathR/To-Do/stargazers",
        "contributors_url": "https://api.github.com/repos/SaiBarathR/To-Do/contributors",
        "subscribers_url": "https://api.github.com/repos/SaiBarathR/To-Do/subscribers",
        "subscription_url": "https://api.github.com/repos/SaiBarathR/To-Do/subscription",
        "commits_url": "https://api.github.com/repos/SaiBarathR/To-Do/commits{/sha}",
        "git_commits_url": "https://api.github.com/repos/SaiBarathR/To-Do/git/commits{/sha}",
        "comments_url": "https://api.github.com/repos/SaiBarathR/To-Do/comments{/number}",
        "issue_comment_url": "https://api.github.com/repos/SaiBarathR/To-Do/issues/comments{/number}",
        "contents_url": "https://api.github.com/repos/SaiBarathR/To-Do/contents/{+path}",
        "compare_url": "https://api.github.com/repos/SaiBarathR/To-Do/compare/{base}...{head}",
        "merges_url": "https://api.github.com/repos/SaiBarathR/To-Do/merges",
        "archive_url": "https://api.github.com/repos/SaiBarathR/To-Do/{archive_format}{/ref}",
        "downloads_url": "https://api.github.com/repos/SaiBarathR/To-Do/downloads",
        "issues_url": "https://api.github.com/repos/SaiBarathR/To-Do/issues{/number}",
        "pulls_url": "https://api.github.com/repos/SaiBarathR/To-Do/pulls{/number}",
        "milestones_url": "https://api.github.com/repos/SaiBarathR/To-Do/milestones{/number}",
        "notifications_url": "https://api.github.com/repos/SaiBarathR/To-Do/notifications{?since,all,participating}",
        "labels_url": "https://api.github.com/repos/SaiBarathR/To-Do/labels{/name}",
        "releases_url": "https://api.github.com/repos/SaiBarathR/To-Do/releases{/id}",
        "deployments_url": "https://api.github.com/repos/SaiBarathR/To-Do/deployments",
        "created_at": "2021-02-03T10:49:49Z",
        "updated_at": "2023-07-09T17:15:48Z",
        "pushed_at": "2021-02-03T10:50:00Z",
        "git_url": "git://github.com/SaiBarathR/To-Do.git",
        "ssh_url": "git@github.com:SaiBarathR/To-Do.git",
        "clone_url": "https://github.com/SaiBarathR/To-Do.git",
        "svn_url": "https://github.com/SaiBarathR/To-Do",
        "homepage": "",
        "size": 1,
        "stargazers_count": 1,
        "watchers_count": 1,
        "language": "Python",
        "has_issues": true,
        "has_projects": true,
        "has_downloads": true,
        "has_wiki": true,
        "has_pages": false,
        "has_discussions": false,
        "forks_count": 0,
        "mirror_url": null,
        "archived": false,
        "disabled": false,
        "open_issues_count": 0,
        "license": null,
        "allow_forking": true,
        "is_template": false,
        "web_commit_signoff_required": false,
        "topics": [
            "pysimplegui",
            "sqllite3"
        ],
        "visibility": "public",
        "forks": 0,
        "open_issues": 0,
        "watchers": 1,
        "default_branch": "master"
    }
]

export const professionalProjectDetails = [{
    name: "Agent Portal - Ozonetel Communications",
    created_at: new Date("2023-02-06"),
    id: 1,
    language: "Javascript",
    description: "Agent Portal is a cloud-based call center solution that provides: 1. WebRTC calls, chats, and notifications for seamless communication. 2. Multiple types of campaigns, such as outbound, inbound, progressive, blended, and predictive for different business needs. 3. Conference and transfer functions for collaboration and customer service. 4. Interactive charts and graphs for data visualisation and analysis.",
    topics: ["Redux", "Websocket", "WebRTC", "Service Worker", "TypeScript", "React"]

},
{
    name: "Admin Portal - Ozonetel Communications",
    created_at: new Date("2022-09-05"),
    id: 2,
    language: "Javascript",
    description: "Admin Portal is a cloud-based call center solution to manage the agents from agent protal: This web application is used by more than 200,000 people to automate agent workloads and view analysis and performace of agents in a given organization. It allows them to view their performance metrics, schedule their shifts, access training materials, and communicate with their supervisors and peers. The site is perfectly optimised for speed and performance, responsiveness and follows the best practices of web development.",
    topics: ["Websocket", "React", "Formik-Mui-AgGrid", "TypeScript", "Chat.js", "Axios"]
},
{
    name: "WhatsApp Templates - Ozonetel Communications",
    created_at: new Date("2023-03-27"),
    id: 3,
    language: "Javascript",
    description: "Whatapp Templates are used to create and manage pre-configured templates for Agents from a call center to use them to connect with customers. It can handle multiple languages with text, voice, pictures, videos and Agent can preview the templates before saving.",
    topics: ["Webpack", "React", "TypeScript", "REST APIs", "HTML-CSS"]
},
{
    name: "Chat Bot - Ozonetel Communications",
    created_at: new Date("2023-05-19"),
    id: 3,
    language: "Javascript",
    description: "Created this chat bot for Ozonetel Partners, where customers can connect to get information about products and services of partner companies and they can subscribe to podcasts, fill forms or connect to an any live agent to learn more. All partner can just edit the config file and ready to go with their own version of chatbot according to their requirements.",
    topics: ["Websocket", "React", "TypeScript", "REST APIs", "axios","Webpack"]
},

]